[package]
name = "chars_counter"
version = "0.1.0"
edition = "2021"

homepage = "https://github.com/Ztry8/characters_counting"
repository = "https://github.com/Ztry8/characters_counting"
readme = "README.md"

[dependencies]
# None
